// SPDX-License-Identifier: GPL-2.0-or-later

//! Renders a systemd `.service` unit for an rclone mount.
//!
//! Shape:
//! - `Type=notify` (rclone calls `sd_notify` when ready since 1.55)
//! - `LoadCredentialEncrypted=` references the encrypted blob; systemd decrypts
//!   into `%d/rclone-conf` (== `$CREDENTIALS_DIRECTORY`) at unit start.
//! - `ExecStart` passes that path via `--config` so rclone reads its remote
//!   definition (including any password) from a tmpfs-backed file with the
//!   cleartext never touching persistent disk.
//! - `ExecStop` uses `fusermount3 -uz` (lazy unmount) to detach — a plain
//!   `-u` fails the whole unit with "Device or resource busy" if anything
//!   still has a file open inside the mount at the moment it's stopped.
//!
//! The mountpoint, credential path, and rclone binary location vary between
//! user and system scope; callers pass a [`Context`] holding the resolved
//! paths and specifier strings so the same `Mount` struct renders either form.
//!
//! A mount's `subpath` never appears in the unit file's text: when non-empty,
//! [`crate::backend`] embeds it as an rclone `alias` remote's `remote =
//! source:subpath` option inside the (already control-character-validated)
//! encrypted config blob, and `ExecStart` here just references that alias by
//! name (see [`mount_alias_name`]) instead of interpolating raw path text
//! into `Exec*=`. Only the mountpoint itself still appears as unit-file
//! text — rclone's `mount` subcommand has no config/env-var alternative to
//! taking it as a positional argument.

use crate::mount::{CacheMode, Mount};
use crate::{Error, Result};
use std::fmt::Write;

/// Per-scope rendering parameters.
pub struct Context {
    /// Absolute path or systemd specifier (e.g. `%h/...`) to the encrypted
    /// credential blob for the mount's source. Loaded as `LoadCredentialEncrypted=`.
    pub credential_path: String,
    /// Path to the rclone binary. Defaults to `/usr/bin/rclone` if you use [`Context::default`].
    pub rclone_binary: String,
    /// Path to the fusermount binary used at ExecStop. Either `fusermount` or `fusermount3`.
    pub fusermount_binary: String,
}

impl Default for Context {
    fn default() -> Self {
        Self {
            credential_path: String::new(),
            rclone_binary: "/usr/bin/rclone".into(),
            fusermount_binary: "/usr/bin/fusermount3".into(),
        }
    }
}

/// Validate a mount or source name against the helper-enforced pattern:
/// `^[a-z0-9][a-z0-9-]{0,62}$`. Reused by both the in-process write paths
/// and the helper's D-Bus methods so the invariant is checked twice.
pub fn validate_name(name: &str) -> Result<()> {
    let ok = !name.is_empty()
        && name.len() <= 63
        && name.bytes().enumerate().all(|(i, b)| {
            if i == 0 {
                matches!(b, b'0'..=b'9' | b'a'..=b'z')
            } else {
                matches!(b, b'0'..=b'9' | b'a'..=b'z' | b'-')
            }
        });
    if ok {
        Ok(())
    } else {
        Err(Error::InvalidName(name.to_string()))
    }
}

/// Reject a control character (newline, CR, NUL, ...) in a value that's
/// about to be embedded in a generated systemd unit file. Unit files are
/// parsed line-by-line, so `quote_unit_arg`'s quoting only protects against
/// whitespace being split into extra argv words — it can't stop a literal
/// embedded newline from ending the `Exec*=` line early and starting a new
/// (attacker-chosen) directive on the next one. Rejecting the character
/// outright is simpler and safer than trying to escape it away.
pub fn reject_control_chars(field: &str, value: &str) -> Result<()> {
    if value.chars().any(|c| c.is_control()) {
        Err(Error::Systemd(format!(
            "{field} can't contain control characters (like a newline)."
        )))
    } else {
        Ok(())
    }
}

/// The rclone remote name a subpath mount's `alias` config entry is stored
/// under (see [`crate::backend`]'s credential-blob builder). `MOUNT_` is an
/// uppercase prefix a valid mount/source name (`^[a-z0-9][a-z0-9-]*$`,
/// lowercase only) can never collide with, so this can never accidentally
/// name-clash with the source's own section in the same config blob.
pub fn mount_alias_name(mount_name: &str) -> String {
    format!("MOUNT_{mount_name}")
}

pub fn render(mount: &Mount, ctx: &Context) -> Result<String> {
    validate_name(&mount.name)?;
    validate_name(&mount.source)?;
    let mountpoint = mount.mountpoint.to_str().ok_or_else(|| {
        Error::Systemd(format!(
            "mountpoint is not valid UTF-8: {:?}",
            mount.mountpoint
        ))
    })?;
    reject_control_chars("The mount point", mountpoint)?;

    let mountpoint = systemd_mountpoint(mountpoint);
    let exec_start = build_exec_start(mount, ctx, &mountpoint);
    let quoted_mountpoint = quote_unit_arg(&mountpoint);

    let mut out = String::new();
    let _ = writeln!(
        out,
        "# Generated by rclone-mounts. Do not edit; regenerated on every apply."
    );
    let _ = writeln!(out, "[Unit]");
    let _ = writeln!(out, "Description=rclone mount: {}", mount.name);
    let _ = writeln!(out, "After=network-online.target");
    let _ = writeln!(out, "Wants=network-online.target");
    let _ = writeln!(out);

    let _ = writeln!(out, "[Service]");
    let _ = writeln!(out, "Type=notify");
    // A previous rclone process can die while still attached at the kernel
    // level, leaving the mountpoint as a dead FUSE endpoint ("Transport
    // endpoint is not connected") that blocks even `mkdir`/`stat` on it —
    // clear that before anything else. The leading `-` tells systemd to
    // ignore this command's exit code: it fails harmlessly when there's
    // nothing stale to unmount, which is the common case.
    let _ = writeln!(
        out,
        "ExecStartPre=-{} -uz {quoted_mountpoint}",
        ctx.fusermount_binary
    );
    let _ = writeln!(out, "ExecStartPre=/usr/bin/mkdir -p {quoted_mountpoint}");
    let _ = writeln!(
        out,
        "LoadCredentialEncrypted=rclone-conf:{}",
        ctx.credential_path
    );
    let _ = writeln!(out, "ExecStart={exec_start}");
    // Lazy unmount (`-z`): a plain `-u` refuses with "Device or resource
    // busy" if anything still has a file open inside the mount (a viewer,
    // a file manager's current directory, …) at the moment we stop it. `-z`
    // detaches it from the namespace immediately and lets any in-flight
    // handles finish in the background instead, so an intentional Stop
    // doesn't get marked as a failed unit just because something was open.
    let _ = writeln!(
        out,
        "ExecStop={} -uz {quoted_mountpoint}",
        ctx.fusermount_binary
    );
    // rclone exits via SIGTERM (status 143) when systemd stops it, which is
    // the normal/expected shutdown path here — without this, systemd has no
    // way to tell that apart from a crash and marks the unit "Failed" on
    // every ordinary Stop.
    let _ = writeln!(out, "SuccessExitStatus=143");
    let _ = writeln!(out, "Restart=on-failure");
    let _ = writeln!(out, "RestartSec=10");
    let _ = writeln!(out);

    let _ = writeln!(out, "[Install]");
    let _ = writeln!(out, "WantedBy=default.target");

    Ok(out)
}

fn build_exec_start(mount: &Mount, ctx: &Context, mountpoint: &str) -> String {
    // Empty subpath mounts the source directly; a non-empty one references
    // the `alias` remote `crate::backend` folded into the source's config
    // blob (`remote = source:subpath`) instead of interpolating the subpath
    // text here — see the module doc comment.
    let remote_spec = if mount.subpath.is_empty() {
        format!("{}:", mount.source)
    } else {
        format!("{}:", mount_alias_name(&mount.name))
    };
    let mut parts: Vec<String> = vec![
        ctx.rclone_binary.clone(),
        "mount".into(),
        "--config=%d/rclone-conf".into(),
        quote_unit_arg(&remote_spec),
        quote_unit_arg(mountpoint),
        format!(
            "--vfs-cache-mode={}",
            cache_mode_str(mount.options.cache_mode)
        ),
        // rclone's global flag is --log-systemd (routes logs to the journal and
        // suppresses its own timestamps). NB: not --systemd-log.
        "--log-systemd".into(),
    ];

    if let Some(mb) = mount.options.cache_max_size_mb {
        parts.push(format!("--vfs-cache-max-size={mb}M"));
    }
    if let Some(secs) = mount.options.dir_cache_time_secs {
        parts.push(format!("--dir-cache-time={secs}s"));
    }
    if let Some(umask) = mount.options.umask {
        parts.push(format!("--umask={umask:03o}"));
    }
    if mount.options.read_only {
        parts.push("--read-only".into());
    }

    parts.join(" ")
}

/// systemd does not expand `~`. Map a leading `~` to the `%h` (home) specifier
/// so the unit resolves the mountpoint at runtime as the owning user, and
/// escape any other `%` in the user-supplied path so it isn't read as a
/// specifier.
fn systemd_mountpoint(raw: &str) -> String {
    let (prefix, rest) = if raw == "~" {
        ("%h", "")
    } else if let Some(r) = raw.strip_prefix("~/") {
        ("%h/", r)
    } else {
        ("", raw)
    };
    format!("{prefix}{}", rest.replace('%', "%%"))
}

/// Quote a value for use as one word on a systemd `Exec*=` line. Those lines
/// are split on whitespace like a shell command, so an unquoted mountpoint or
/// subpath containing a space (e.g. `~/iCloud Drive`) is silently split into
/// multiple command arguments — `mkdir -p` then creates two directories
/// instead of failing loudly. systemd's unit-file quoting accepts
/// double-quoted strings with C-style `\\`/`\"` escapes (systemd.syntax(7)).
fn quote_unit_arg(raw: &str) -> String {
    if raw
        .chars()
        .any(|c| c.is_whitespace() || matches!(c, '"' | '\\'))
    {
        let escaped = raw.replace('\\', "\\\\").replace('"', "\\\"");
        format!("\"{escaped}\"")
    } else {
        raw.to_string()
    }
}

fn cache_mode_str(mode: CacheMode) -> &'static str {
    match mode {
        CacheMode::Off => "off",
        CacheMode::Minimal => "minimal",
        CacheMode::Writes => "writes",
        CacheMode::Full => "full",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mount::{CacheMode, MountOptions};
    use std::path::PathBuf;

    fn sample_mount() -> Mount {
        Mount {
            name: "work".into(),
            display_name: "Work".into(),
            source: "office-smb".into(),
            subpath: String::new(),
            mountpoint: PathBuf::from("/home/alice/Mounts/work"),
            options: MountOptions::default(),
            enabled: true,
        }
    }

    fn user_ctx() -> Context {
        Context {
            credential_path: "%h/.config/rclone-mounts/credentials/office-smb".into(),
            ..Default::default()
        }
    }

    #[test]
    fn renders_expected_sections() {
        let unit = render(&sample_mount(), &user_ctx()).unwrap();
        assert!(unit.contains("[Unit]\n"));
        assert!(unit.contains("[Service]\n"));
        assert!(unit.contains("[Install]\n"));
        assert!(unit.contains("Description=rclone mount: work\n"));
    }

    #[test]
    fn references_credential_via_load_credential_encrypted() {
        let unit = render(&sample_mount(), &user_ctx()).unwrap();
        assert!(unit.contains(
            "LoadCredentialEncrypted=rclone-conf:%h/.config/rclone-mounts/credentials/office-smb\n"
        ));
        // And the ExecStart reads it back via the %d specifier.
        assert!(unit.contains("--config=%d/rclone-conf"));
    }

    #[test]
    fn includes_mount_path_in_pre_and_stop() {
        let unit = render(&sample_mount(), &user_ctx()).unwrap();
        assert!(unit.contains("ExecStartPre=/usr/bin/mkdir -p /home/alice/Mounts/work\n"));
        assert!(unit.contains("ExecStop=/usr/bin/fusermount3 -uz /home/alice/Mounts/work\n"));
    }

    #[test]
    fn treats_sigterm_shutdown_as_success() {
        let unit = render(&sample_mount(), &user_ctx()).unwrap();
        assert!(unit.contains("SuccessExitStatus=143\n"));
    }

    #[test]
    fn clears_a_stale_mount_before_mkdir() {
        let unit = render(&sample_mount(), &user_ctx()).unwrap();
        // The `-` prefix means systemd ignores this command's exit code —
        // it's expected to fail (nothing to unmount) most of the time.
        assert!(unit.contains("ExecStartPre=-/usr/bin/fusermount3 -uz /home/alice/Mounts/work\n"));
        // And it must run before the mkdir, or a still-attached stale mount
        // would make the mkdir fail with "Transport endpoint is not connected".
        let stale_unmount_pos = unit.find("ExecStartPre=-/usr/bin/fusermount3").unwrap();
        let mkdir_pos = unit.find("ExecStartPre=/usr/bin/mkdir").unwrap();
        assert!(stale_unmount_pos < mkdir_pos);
    }

    #[test]
    fn exec_start_uses_correct_systemd_log_flag() {
        let unit = render(&sample_mount(), &user_ctx()).unwrap();
        // Must be rclone's real flag; --systemd-log is rejected as unknown.
        assert!(unit.contains("--log-systemd"));
        assert!(!unit.contains("--systemd-log"));
    }

    #[test]
    fn options_appear_in_exec_start() {
        let mut m = sample_mount();
        m.options = MountOptions {
            cache_mode: CacheMode::Full,
            cache_max_size_mb: Some(4096),
            dir_cache_time_secs: Some(60),
            umask: Some(0o077),
            read_only: true,
        };
        let unit = render(&m, &user_ctx()).unwrap();
        assert!(unit.contains("--vfs-cache-mode=full"));
        assert!(unit.contains("--vfs-cache-max-size=4096M"));
        assert!(unit.contains("--dir-cache-time=60s"));
        assert!(unit.contains("--umask=077"));
        assert!(unit.contains("--read-only"));
    }

    #[test]
    fn tilde_mountpoint_becomes_home_specifier() {
        let mut m = sample_mount();
        m.mountpoint = PathBuf::from("~/.mnt/test");
        let unit = render(&m, &user_ctx()).unwrap();
        assert!(unit.contains("ExecStartPre=/usr/bin/mkdir -p %h/.mnt/test\n"));
        assert!(unit.contains("ExecStop=/usr/bin/fusermount3 -uz %h/.mnt/test\n"));
        assert!(unit.contains(" %h/.mnt/test "));
        // No literal tilde should survive into the rendered unit.
        assert!(!unit.contains("~/.mnt/test"));
    }

    #[test]
    fn mountpoint_with_space_is_quoted_as_one_argument() {
        let mut m = sample_mount();
        m.mountpoint = PathBuf::from("/home/alice/iCloud Drive");
        let unit = render(&m, &user_ctx()).unwrap();
        assert!(unit.contains("ExecStartPre=/usr/bin/mkdir -p \"/home/alice/iCloud Drive\"\n"));
        assert!(unit.contains("ExecStop=/usr/bin/fusermount3 -uz \"/home/alice/iCloud Drive\"\n"));
        assert!(unit.contains("\"/home/alice/iCloud Drive\""));
        // Unquoted, systemd would split this into two mkdir arguments.
        assert!(!unit.contains("-p /home/alice/iCloud Drive\n"));
    }

    #[test]
    fn non_empty_subpath_references_the_alias_remote_not_raw_text() {
        let mut m = sample_mount();
        m.subpath = "My Documents".into();
        let unit = render(&m, &user_ctx()).unwrap();
        // The subpath text itself never appears in the unit; ExecStart
        // references the alias remote by name instead (its `remote =
        // office-smb:My Documents` lives in the encrypted config blob —
        // see `crate::backend`).
        assert!(!unit.contains("My Documents"));
        assert!(unit.contains(&format!("{}:", mount_alias_name("work"))));
    }

    #[test]
    fn empty_subpath_mounts_the_source_directly() {
        let unit = render(&sample_mount(), &user_ctx()).unwrap();
        assert!(unit.contains("office-smb:"));
        assert!(!unit.contains(&mount_alias_name("work")));
    }

    #[test]
    fn name_validation_rejects_path_traversal_attempts() {
        assert!(validate_name("../etc/passwd").is_err());
        assert!(validate_name("work/sub").is_err());
        assert!(validate_name("work.service").is_err());
        assert!(validate_name("WORK").is_err());
        assert!(validate_name("").is_err());
        assert!(validate_name("-leading-dash").is_err());
    }

    #[test]
    fn name_validation_accepts_valid_names() {
        assert!(validate_name("work").is_ok());
        assert!(validate_name("office-smb").is_ok());
        assert!(validate_name("a1").is_ok());
        assert!(validate_name(&"a".repeat(63)).is_ok());
        assert!(validate_name(&"a".repeat(64)).is_err());
    }

    #[test]
    fn render_rejects_bad_names() {
        let mut m = sample_mount();
        m.name = "../bad".into();
        assert!(render(&m, &user_ctx()).is_err());

        let mut m = sample_mount();
        m.source = "../bad".into();
        assert!(render(&m, &user_ctx()).is_err());
    }

    #[test]
    fn render_rejects_newline_in_mountpoint() {
        let mut m = sample_mount();
        m.mountpoint = PathBuf::from("/tmp/x\nExecStartPost=/bin/touch /tmp/pwned");
        assert!(render(&m, &user_ctx()).is_err());
    }

    #[test]
    fn render_rejects_other_control_chars_in_mountpoint() {
        let mut m = sample_mount();
        m.mountpoint = PathBuf::from("/tmp/a\rb");
        assert!(render(&m, &user_ctx()).is_err());
        m.mountpoint = PathBuf::from("/tmp/a\0b");
        assert!(render(&m, &user_ctx()).is_err());
    }
}
