// SPDX-License-Identifier: GPL-2.0-or-later

//! Renders a systemd `.service` unit for an rclone mount.
//!
//! Shape:
//! - `Type=notify` (rclone calls `sd_notify` when ready since 1.55)
//! - `LoadCredentialEncrypted=` references the encrypted blob; systemd decrypts
//!   into `%d/rclone-conf` (== `$CREDENTIALS_DIRECTORY`) at unit start.
//! - `ExecStart` passes that path via `--config` so rclone reads its remote
//!   definition (including any password) from a tmpfs-backed file with the
//!   cleartext never touching persistent disk.
//! - `ExecStop` uses `fusermount3 -u` to detach.
//!
//! The mountpoint, credential path, and rclone binary location vary between
//! user and system scope; callers pass a [`Context`] holding the resolved
//! paths and specifier strings so the same `Mount` struct renders either form.

use crate::mount::{CacheMode, Mount};
use crate::{Error, Result};
use std::fmt::Write;

/// Per-scope rendering parameters.
pub struct Context {
    /// Absolute path or systemd specifier (e.g. `%h/...`) to the encrypted
    /// credential blob for the mount's source. Loaded as `LoadCredentialEncrypted=`.
    pub credential_path: String,
    /// Path to the rclone binary. Defaults to `/usr/bin/rclone` if you use [`Context::default`].
    pub rclone_binary: String,
    /// Path to the fusermount binary used at ExecStop. Either `fusermount` or `fusermount3`.
    pub fusermount_binary: String,
}

impl Default for Context {
    fn default() -> Self {
        Self {
            credential_path: String::new(),
            rclone_binary: "/usr/bin/rclone".into(),
            fusermount_binary: "/usr/bin/fusermount3".into(),
        }
    }
}

/// Validate a mount or source name against the helper-enforced pattern:
/// `^[a-z0-9][a-z0-9-]{0,62}$`. Reused by both the in-process write paths
/// and the helper's D-Bus methods so the invariant is checked twice.
pub fn validate_name(name: &str) -> Result<()> {
    let ok = !name.is_empty()
        && name.len() <= 63
        && name.bytes().enumerate().all(|(i, b)| {
            if i == 0 {
                matches!(b, b'0'..=b'9' | b'a'..=b'z')
            } else {
                matches!(b, b'0'..=b'9' | b'a'..=b'z' | b'-')
            }
        });
    if ok {
        Ok(())
    } else {
        Err(Error::InvalidName(name.to_string()))
    }
}

pub fn render(mount: &Mount, ctx: &Context) -> Result<String> {
    validate_name(&mount.name)?;
    validate_name(&mount.source)?;
    let mountpoint = mount.mountpoint.to_str().ok_or_else(|| {
        Error::Systemd(format!("mountpoint is not valid UTF-8: {:?}", mount.mountpoint))
    })?;

    let exec_start = build_exec_start(mount, ctx, mountpoint);

    let mut out = String::new();
    let _ = writeln!(out, "# Generated by rclone-mounts. Do not edit; regenerated on every apply.");
    let _ = writeln!(out, "[Unit]");
    let _ = writeln!(out, "Description=rclone mount: {}", mount.name);
    let _ = writeln!(out, "After=network-online.target");
    let _ = writeln!(out, "Wants=network-online.target");
    let _ = writeln!(out);

    let _ = writeln!(out, "[Service]");
    let _ = writeln!(out, "Type=notify");
    let _ = writeln!(out, "ExecStartPre=/usr/bin/mkdir -p {mountpoint}");
    let _ = writeln!(
        out,
        "LoadCredentialEncrypted=rclone-conf:{}",
        ctx.credential_path
    );
    let _ = writeln!(out, "ExecStart={exec_start}");
    let _ = writeln!(out, "ExecStop={} -u {mountpoint}", ctx.fusermount_binary);
    let _ = writeln!(out, "Restart=on-failure");
    let _ = writeln!(out, "RestartSec=10");
    let _ = writeln!(out);

    let _ = writeln!(out, "[Install]");
    let _ = writeln!(out, "WantedBy=default.target");

    Ok(out)
}

fn build_exec_start(mount: &Mount, ctx: &Context, mountpoint: &str) -> String {
    let mut parts: Vec<String> = vec![
        ctx.rclone_binary.clone(),
        "mount".into(),
        "--config=%d/rclone-conf".into(),
        format!("{}:", mount.source),
        mountpoint.into(),
        format!("--vfs-cache-mode={}", cache_mode_str(mount.options.cache_mode)),
        "--systemd-log".into(),
    ];

    if let Some(mb) = mount.options.cache_max_size_mb {
        parts.push(format!("--vfs-cache-max-size={mb}M"));
    }
    if let Some(secs) = mount.options.dir_cache_time_secs {
        parts.push(format!("--dir-cache-time={secs}s"));
    }
    if let Some(umask) = mount.options.umask {
        parts.push(format!("--umask={umask:03o}"));
    }
    if mount.options.read_only {
        parts.push("--read-only".into());
    }

    parts.join(" ")
}

fn cache_mode_str(mode: CacheMode) -> &'static str {
    match mode {
        CacheMode::Off => "off",
        CacheMode::Minimal => "minimal",
        CacheMode::Writes => "writes",
        CacheMode::Full => "full",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mount::{CacheMode, MountOptions};
    use std::path::PathBuf;

    fn sample_mount() -> Mount {
        Mount {
            name: "work".into(),
            source: "office-smb".into(),
            mountpoint: PathBuf::from("/home/alice/Mounts/work"),
            options: MountOptions::default(),
            enabled: true,
        }
    }

    fn user_ctx() -> Context {
        Context {
            credential_path: "%h/.config/rclone-mounts/credentials/office-smb".into(),
            ..Default::default()
        }
    }

    #[test]
    fn renders_expected_sections() {
        let unit = render(&sample_mount(), &user_ctx()).unwrap();
        assert!(unit.contains("[Unit]\n"));
        assert!(unit.contains("[Service]\n"));
        assert!(unit.contains("[Install]\n"));
        assert!(unit.contains("Description=rclone mount: work\n"));
    }

    #[test]
    fn references_credential_via_load_credential_encrypted() {
        let unit = render(&sample_mount(), &user_ctx()).unwrap();
        assert!(unit.contains("LoadCredentialEncrypted=rclone-conf:%h/.config/rclone-mounts/credentials/office-smb\n"));
        // And the ExecStart reads it back via the %d specifier.
        assert!(unit.contains("--config=%d/rclone-conf"));
    }

    #[test]
    fn includes_mount_path_in_pre_and_stop() {
        let unit = render(&sample_mount(), &user_ctx()).unwrap();
        assert!(unit.contains("ExecStartPre=/usr/bin/mkdir -p /home/alice/Mounts/work\n"));
        assert!(unit.contains("ExecStop=/usr/bin/fusermount3 -u /home/alice/Mounts/work\n"));
    }

    #[test]
    fn options_appear_in_exec_start() {
        let mut m = sample_mount();
        m.options = MountOptions {
            cache_mode: CacheMode::Full,
            cache_max_size_mb: Some(4096),
            dir_cache_time_secs: Some(60),
            umask: Some(0o077),
            read_only: true,
        };
        let unit = render(&m, &user_ctx()).unwrap();
        assert!(unit.contains("--vfs-cache-mode=full"));
        assert!(unit.contains("--vfs-cache-max-size=4096M"));
        assert!(unit.contains("--dir-cache-time=60s"));
        assert!(unit.contains("--umask=077"));
        assert!(unit.contains("--read-only"));
    }

    #[test]
    fn name_validation_rejects_path_traversal_attempts() {
        assert!(validate_name("../etc/passwd").is_err());
        assert!(validate_name("work/sub").is_err());
        assert!(validate_name("work.service").is_err());
        assert!(validate_name("WORK").is_err());
        assert!(validate_name("").is_err());
        assert!(validate_name("-leading-dash").is_err());
    }

    #[test]
    fn name_validation_accepts_valid_names() {
        assert!(validate_name("work").is_ok());
        assert!(validate_name("office-smb").is_ok());
        assert!(validate_name("a1").is_ok());
        assert!(validate_name(&"a".repeat(63)).is_ok());
        assert!(validate_name(&"a".repeat(64)).is_err());
    }

    #[test]
    fn render_rejects_bad_names() {
        let mut m = sample_mount();
        m.name = "../bad".into();
        assert!(render(&m, &user_ctx()).is_err());

        let mut m = sample_mount();
        m.source = "../bad".into();
        assert!(render(&m, &user_ctx()).is_err());
    }
}
